In [32]:
import tensorflow as tf

In [33]:
print(tf.__version__)

2.3.1


In [34]:
msg = tf.constant('Hello, world!!')
print(type(msg))
tf.print(msg)

<class 'tensorflow.python.framework.ops.EagerTensor'>
Hello, world!!


In [35]:
node1 = tf.constant(2, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)
print("The sum is : ")
tf.print(node3)

The sum is : 
7


In [36]:
node = tf.Variable(tf.zeros([2,2]))
print("Before addition")
tf.print(node)

node.assign(node + tf.Variable(tf.ones([2,2])))
print("After addition")
tf.print(node)

Before addition
[[0 0]
 [0 0]]
After addition
[[1 1]
 [1 1]]


In [44]:
import numpy as np

node1 = tf.constant(np.array([(2,2,2),(2,2,2),(2,2,2)]), dtype=tf.float32)
node2 = tf.constant(np.array([(1,1,1),(1,1,1),(1,1,1)]), dtype=tf.float32)
node_mul = tf.matmul(node1, node2)
print('Multiplication : ')
tf.print(node_mul)

node_add = tf.add(node1, node2)
print('')
print("Addition :")
tf.print(node_add)

print('')
print("Determinant :")
node_det = tf.linalg.det(node1)
tf.print(node_det)

Multiplication : 
[[6 6 6]
 [6 6 6]
 [6 6 6]]

Addition :
[[3 3 3]
 [3 3 3]
 [3 3 3]]

Determinant :
0
