### Three powerful packages
- Numpy
- Pandas
- Matplotlib

## Numpy

- Used for scientific computing
- Helps to create/ manage N-dimensional array

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
print(x.shape)

(4,)


In [8]:
y = np.array([[1,2],[3,4]])

In [9]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [14]:
z = np.array([[1+0.j,2+5.j]])

In [11]:
print(z)
print(z.shape)

[1.+0.j]
(1,)


In [17]:
a = np.zeros((2,3))

In [18]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
print(a.shape)

(2, 3)


In [20]:
b = np.ones([2,3], dtype=int)

In [21]:
print(b)

[[1 1 1]
 [1 1 1]]


In [22]:
d = np.eye(3) ## identity matrix

In [23]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
e = np.arange(10) ## Range

In [25]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
e = np.arange(12, 21)

In [28]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [29]:
e = np.arange(5,20,3)

In [30]:
print(e)

[ 5  8 11 14 17]


In [34]:
f = np.linspace(1,20,7) ## It create intervals

In [35]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [37]:
g = np.random.random((3,4))

In [38]:
print(g)

[[0.36702753 0.88071871 0.68284154 0.32092849]
 [0.35327321 0.86387965 0.25636674 0.17570985]
 [0.15336702 0.91638412 0.80857437 0.05800689]]


In [41]:
h = np.random.random((3,4))

In [49]:
print(h.reshape(2,2,3))

[[[0.23575685 0.03898623 0.73879721]
  [0.46424438 0.11361272 0.382253  ]]

 [[0.95602628 0.40903087 0.94652141]
  [0.43452741 0.9795222  0.36595466]]]


In [50]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [51]:
print(x[-1])

11


In [55]:
x.resize(3,4)

In [56]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
print(x[-1,-1])

11


In [59]:
print(x[2][3])

11


In [64]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [68]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [69]:
print(y[10:15])

[11 12 13 14 15]


In [71]:
print(y[-5:])

[21 22 23 24 25]


In [73]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [74]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [76]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [86]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [98]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [99]:
print(y[:,-1])

[ 5 10 15 20 25]


In [101]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [102]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [104]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [107]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [109]:
print(a>3)

[False False False  True  True]


In [110]:
a = np.arange(0,4).reshape((2,2))

In [111]:
b = np.eye(2)

In [112]:
print(a*b) ##Wrong

[[0. 0.]
 [0. 3.]]


In [113]:
print(np.dot(a,b)) ##Matrix multiplication

[[0. 1.]
 [2. 3.]]


In [118]:
x = np.arange(1,10).reshape(3,3)

In [119]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [120]:
print(x.sum())

45


In [122]:
print(x.sum(axis=0))

[12 15 18]


In [123]:
print(x.sum(axis=1))

[ 6 15 24]


In [124]:
print(x.sum(axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [125]:
x = np.arange(1,19).reshape(3,3,2)

In [129]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [127]:
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [131]:
x = np.arange(1,10).reshape(3,3)

In [133]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [134]:
print(x.max(axis=0))

[7 8 9]


In [135]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [136]:
print(np.linlog.inv(x))

AttributeError: module 'numpy' has no attribute 'linlog'