In [16]:
import os
import cv2
import numpy as np
from PIL import Image

In [17]:
x = []
y = []
basePath = './dataset/'
for folder in os.scandir(basePath):
    if folder.is_dir():
        for file in os.scandir(folder):
            img = Image.open(file.path)
            features = np.array(img.resize((120,120))) / 255.0
            x.append(features)
            y.append(folder.name)
            
print(x)
print(y)

[array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]]), array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
  

In [18]:
x = np.array(x)

In [19]:
print(x.shape)
print(np.shape(y))

(42, 120, 120, 3)
(42,)


In [20]:
from sklearn.preprocessing import LabelBinarizer
labelBinarizer = LabelBinarizer()
y = labelBinarizer.fit_transform(y)

import tensorflow as tf
y=tf.keras.utils.to_categorical(y)
print(y)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(np.array(x), np.array(y), 
                                                    test_size=0.2, random_state=42)

In [24]:
from tensorflow.python.keras import layers
from tensorflow.python.keras import models

import random

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

cnnModel = models.Sequential()
cnnModel.add(layers.Conv2D(10, (3,3), activation="relu", 
                           input_shape=(120,120,3)))
cnnModel.add(layers.MaxPooling2D((2,2)))
cnnModel.add(layers.Conv2D(64, (3,3), activation="relu"))
cnnModel.add(layers.MaxPooling2D((2,2)))
cnnModel.add(layers.Conv2D(64, (3,3), activation="relu"))
cnnModel.add(layers.Flatten())
cnnModel.add(layers.Dense(64, activation="relu"))
cnnModel.add(layers.Dense(32, activation="relu"))
cnnModel.add(layers.Dense(2, activation="softmax"))
cnnModel.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 118, 118, 10)      280       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 59, 59, 10)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 57, 57, 64)        5824      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 26, 26, 64)        36928     
_________________________________________________________________
flatten (Flatten)            (None, 43264)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                2

In [25]:
cnnModel.compile(optimizer="adam", 
                loss="binary_crossentropy",
                metrics=["accuracy"])

In [26]:
cnnModel.fit(x_train, y_train, epochs=20, batch_size=32)

Epoch 1/20
2/2 [==============================] - 0s 11ms/step - loss: 0.6990 - accuracy: 0.5152
Epoch 2/20
2/2 [==============================] - 0s 10ms/step - loss: 1.1921 - accuracy: 0.5455
Epoch 3/20
2/2 [==============================] - 0s 10ms/step - loss: 0.9060 - accuracy: 0.5455
Epoch 4/20
2/2 [==============================] - 0s 9ms/step - loss: 0.5939 - accuracy: 0.5455
Epoch 5/20
2/2 [==============================] - 0s 10ms/step - loss: 0.4714 - accuracy: 0.6667
Epoch 6/20
2/2 [==============================] - 0s 9ms/step - loss: 0.4143 - accuracy: 0.6667
Epoch 7/20
2/2 [==============================] - 0s 10ms/step - loss: 0.2220 - accuracy: 0.9697
Epoch 8/20
2/2 [==============================] - 0s 13ms/step - loss: 0.1158 - accuracy: 1.0000
Epoch 9/20
2/2 [==============================] - 0s 10ms/step - loss: 0.0458 - accuracy: 0.9697
Epoch 10/20
2/2 [==============================] - 0s 12ms/step - loss: 0.0404 - accuracy: 0.9697
Epoch 11/20
2/2 [==============

In [27]:
testLoss, testAccuracy = cnnModel.evaluate(x_test, y_test)
print(testAccuracy)

1/1 [==============================] - 0s 1ms/step - loss: 3.8212e-04 - accuracy: 1.0000
1.0


In [28]:
cnnModel.save_weights('model/weights.hf5')

In [29]:
y_pred = cnnModel.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [30]:
tf.math.confusion_matrix(np.argmax(y_test, axis=1),y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 0],
       [0, 5]])>

In [38]:
x_t = []
img = Image.open('dataset/lemon/index4.jpg')
x_t.append(np.array(img.resize((120,120))) / 255.0)

x_t = np.array(x_t)
print(x_t.shape)

(1, 120, 120, 3)


In [39]:
y_t = cnnModel.predict_classes(x_t)

In [40]:
print(y_t)

[0]
