In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
import random
import numpy as np

In [2]:
seed = 42
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

In [3]:
##Load mnist dataset
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [4]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [16]:
x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

In [20]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [21]:
cnnModel = models.Sequential()

cnnModel.add(layers.Conv2D(10, (3,3), activation="relu", 
                           input_shape=(28,28,1)))

cnnModel.add(layers.MaxPooling2D((2,2)))

cnnModel.add(layers.Conv2D(64, (3,3), activation="relu"))

cnnModel.add(layers.MaxPooling2D((2,2)))

cnnModel.add(layers.Conv2D(64, (3,3), activation="relu"))

cnnModel.add(layers.Flatten())

cnnModel.add(layers.Dense(64, activation="relu"))

cnnModel.add(layers.Dense(32, activation="relu"))

cnnModel.add(layers.Dense(10, activation="softmax"))

cnnModel.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 26, 26, 10)        100       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 13, 13, 10)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 11, 11, 64)        5824      
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten_3 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 64)               

In [22]:
cnnModel.compile(optimizer="adam", 
                loss="categorical_crossentropy",
                metrics=["accuracy"])

In [23]:
cnnModel.fit(x_train, y_train, epochs=20, batch_size=28)

Epoch 1/20
2143/2143 [==============================] - 15s 7ms/step - loss: 0.2866 - accuracy: 0.9256
Epoch 2/20
2143/2143 [==============================] - 16s 8ms/step - loss: 0.0708 - accuracy: 0.9791
Epoch 3/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0550 - accuracy: 0.9840
Epoch 4/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0468 - accuracy: 0.9862
Epoch 5/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0383 - accuracy: 0.9886
Epoch 6/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0326 - accuracy: 0.9902
Epoch 7/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0313 - accuracy: 0.9907
Epoch 8/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0273 - accuracy: 0.9919
Epoch 9/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0250 - accuracy: 0.9926
Epoch 10/20
2143/2143 [==============================] - 16s 7ms/step - l

In [24]:
testLoss, testAccuracy = cnnModel.evaluate(x_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0551 - accuracy: 0.9908


In [25]:
cnnModel.save_weights('models/weights.h5')

In [26]:
cnnModel.save('models/arch-weights.h5')

In [38]:
y_pred = cnnModel.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [39]:
print(y_pred)

[7 2 1 ... 4 5 6]


In [40]:
tf.math.confusion_matrix(np.argmax(y_test, axis=1),y_pred)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 977,    1,    0,    1,    0,    0,    0,    1,    0,    0],
       [   0, 1131,    1,    1,    0,    0,    0,    2,    0,    0],
       [   0,    1, 1022,    0,    1,    0,    2,    4,    2,    0],
       [   0,    0,    2, 1001,    0,    4,    0,    2,    1,    0],
       [   0,    0,    1,    0,  965,    0,    3,    1,    0,   12],
       [   0,    0,    0,    5,    0,  884,    1,    0,    1,    1],
       [   5,    3,    0,    0,    1,    1,  947,    0,    1,    0],
       [   0,    2,    2,    0,    1,    0,    0, 1020,    0,    3],
       [   0,    0,    0,    3,    0,    1,    0,    2,  966,    2],
       [   1,    0,    1,    1,    6,    1,    0,    4,    0,  995]])>

In [44]:
print(cnnModel.predict_classes(x_test[:1]))

[7]
